from ctm.utils import *

CTMFULLDEFAULTPRESET = {
	0:Map(),
	1:Top()+Left()+Down(),
	2:Top()+Down(),
	3:Top()+Right()+Down(),
	4:Top()+Left()+DownRight(),
	5:Top()+Right()+DownLeft(),
	6:Left()+TopRight()+DownRight(),
	7:Top()+DownLeft()+DownRight(),
	8:TopLeft()+DownLeft()+DownRight(),
	9:DownLeft()+TopLeft()+TopRight(),
	10:TopLeft()+DownLeft(),
	11:DownLeft()+DownRight(),
	12:Left()+Right()+Top(),
	13:Top()+Left(),
	14:Top(),
	15:Top()+Right(),
	16:Left()+Down()+TopRight(),
	17:Right()+Down()+TopLeft(),
	18:Down()+TopLeft()+TopRight(),
	19:Right()+TopLeft()+DownLeft(),
	20:DownLeft()+DownRight()+TopRight(),
	21:TopLeft()+TopRight()+DownRight(),
	22:TopLeft()+TopRight(),
	23:TopRight()+DownRight(),
	24:Left()+Right(),
	25:Left(),
	26:Map([[0,0,0],[0,0,0],[0,0,0]]),
	27:Right(),
	28:Left()+TopRight(),
	29:Top()+DownRight(),
	30:Left()+DownRight(),
	31:Top()+DownLeft(),
	32:DownRight(),
	33:DownLeft(),
	34:TopLeft()+DownRight(),
	35:TopRight()+DownLeft(),
	36:Left()+Right()+Down(),
	37:Left()+Down(),
	38:Down(),
	39:Down()+Right(),
	40:Down()+TopRight(),
	41:Right()+DownLeft(),
	42:Down()+TopRight(),
	43:Right()+TopLeft(),
	44:TopRight(),
	45:TopLeft(),
	46:TopLeft()+TopRight()+DownLeft()+DownRight()}

# for key in list(CTMFULLDEFAULTPRESET.keys()):
# 	print("\n"+str(key)+"\n")
# 	print(CTMFULLDEFAULTPRESET[key])